# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import ilot.core.manager
import ilot.core.models
import ilot.medias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('actor', models.CharField(max_length=36)),
                ('item', models.CharField(max_length=36)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ilot.medias.models.upload_to)),
                ('file', models.FileField(blank=True, null=True, upload_to=ilot.medias.models.upload_to)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
    ]
