# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
