# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
        ('rules', '0002_attribute_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='webhooks.Webhook', verbose_name='Webhook'),
        ),
        migrations.AlterField(
            model_name='action',
            name='authorize',
            field=models.BooleanField(default=False, verbose_name='Request external authorization'),
        ),
    ]
