# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20180604_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['order']},
        ),
    ]
