# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20180607_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='display_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_fields', to='rules.Attribute'),
        ),
        migrations.AlterField(
            model_name='type',
            name='min_count',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
