# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_auto_20180612_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='regexp_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
