# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_auto_20180617_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trigger',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='type',
            name='min_count',
        ),
        migrations.AddField(
            model_name='trigger',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='authorize',
            field=models.BooleanField(default=False, verbose_name='Request external callback'),
        ),
    ]
