# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0012_auto_20180627_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='replaces',
        ),
        migrations.AddField(
            model_name='status',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='Share with all interfaces'),
        ),
    ]
