# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_auto_20180629_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='image',
        ),
    ]
