# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_remove_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='status',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='rules.Status', verbose_name='A'),
        ),
    ]
