# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_auto_20180715_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='rules.Status'),
        ),
    ]
