# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_auto_20180715_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='left',
            field=models.ForeignKey(db_constraint=False, help_text='Left value', on_delete=django.db.models.deletion.PROTECT, related_name='condition_lefts', to='rules.Property'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Parent condition needed to be true', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='rules.Condition'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='right',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Right value', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condition_rights', to='rules.Property'),
        ),
    ]
