# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0019_auto_20180715_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Attribute value of the selected scope type action', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='rules.Attribute'),
        ),
        migrations.AlterField(
            model_name='property',
            name='scope',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Type used to filter descendants events. Ex: calling an initiative, get the AssignedContributions amount total', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='rules.Type'),
        ),
    ]
