# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0020_auto_20180715_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='actor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='rules.Type', verbose_name='as a '),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='rules.Type', verbose_name='on a '),
        ),
    ]
