# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0022_auto_20180715_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='action',
            field=models.ForeignKey(db_constraint=False, help_text='Action to apply requirements', on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='rules.Action'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='behavior',
            field=models.ForeignKey(db_constraint=False, help_text='Maybe Action to fulfill requirement', on_delete=django.db.models.deletion.PROTECT, related_name='unfullfilled_requirements', to='rules.Action'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='condition',
            field=models.ForeignKey(db_constraint=False, help_text='Condition related', on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='rules.Condition'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='rules.Action', verbose_name='doing'),
        ),
        migrations.AlterField(
            model_name='type',
            name='display_field',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='display_fields', to='rules.Attribute'),
        ),
        migrations.AlterField(
            model_name='type',
            name='package',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='ilot.Package', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_types', to='rules.Type', verbose_name='On a'),
        ),
    ]
