# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import ilot.rules.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0023_auto_20180715_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ilot.rules.models.upload_to),
        ),
    ]
