# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0024_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Request signature'),
        ),
        migrations.AddField(
            model_name='action',
            name='transaction',
            field=models.BooleanField(default=False, verbose_name='Request transaction'),
        ),
    ]
