# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0025_auto_20180725_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='silent',
            field=models.BooleanField(default=False, verbose_name='Silence status in feeds'),
        ),
    ]
