# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0026_status_silent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='package',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='ilot.Package', verbose_name='Package'),
        ),
    ]
