# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grammar', '0006_auto_20180619_1701'),
        ('webhooks', '0001_initial'),
        ('rules', '0010_auto_20180617_1227'),
        ('core', '0014_auto_20180620_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorInferedType',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_types', to='core.Moderation')),
                ('context', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_typed', to='core.Moderation')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_typing', to='core.Moderation')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typed_meta', to='rules.Type')),
            ],
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActorNotification',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('context', models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to='meta.ActorInferedType')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to='core.Moderation')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='webhooks.WebhookRequest', verbose_name='Webhook request')),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrules', to='grammar.Notification')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='actorinferedtype',
            unique_together=set([('context', 'actor', 'type', 'event')]),
        ),
    ]
