# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('process_id', models.CharField(max_length=36)),
                ('actor_id', models.CharField(max_length=36)),
                ('event_id', models.CharField(max_length=36)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
    ]
