# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_messagequeue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagequeue',
            name='event_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
