# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180603_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='datablock',
            name='related',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
