# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_datablock_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='datablock',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
    ]
