# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='method',
            field=models.CharField(choices=[('GET', 'GET/SUB'), ('POST', 'POST/PUB')], default='GET', max_length=6),
        ),
    ]
