# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '__first__'),
        ('webhooks', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('i_did', models.CharField(blank=True, default='You did STATUS on ITEM', max_length=4096, null=True)),
                ('target_did', models.CharField(blank=True, default='ACTOR did STATUS on ITEM', max_length=4096, null=True)),
                ('others_did', models.CharField(blank=True, default='ACTOR did STATUS on ITEM', max_length=4096, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='rules.Status', verbose_name='When')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='rules.Type', verbose_name='on a')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('todo', models.BooleanField(default=False, verbose_name='Is Todo')),
                ('silent', models.BooleanField(default=False, verbose_name='Is silent')),
                ('email', models.BooleanField(default=False, verbose_name='Send email')),
                ('title', models.CharField(blank=True, default='', max_length=156)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Email message')),
                ('condition', models.ForeignKey(blank=True, help_text='Condition to be true to notify by email', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='rules.Condition')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='rules.Status', verbose_name='When')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_targets', to='rules.Type', verbose_name='tell')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='rules.Type', verbose_name='on a')),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='webhooks.Webhook', verbose_name='Webhook')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('description', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('i_label', models.CharField(default='ACTION', help_text='Action button main label <br/>\nex: Create project ...', max_length=4096, verbose_name='Short Button label')),
                ('i_confirmation', models.CharField(default="Lets'do ACTION !", help_text='Action button long label, like a conclusion <br/>\nex: Start your new project', max_length=4096, verbose_name='Confirmation Button label')),
                ('i_title', models.CharField(default='ACTION on ORIGIN', help_text='Action form title <br/>\nex: Create you project !', max_length=4096, verbose_name='Side panel title')),
                ('i_dialog', models.CharField(default='ACTION on ORIGIN', help_text='Action dialog title <br/>\nex: Create you project !', max_length=4096, verbose_name='Dialog title')),
                ('other_title', models.CharField(default='ACTOR is doing ACTION on ITEM', help_text='Description of a user doing something.<br/>\nMainly usefull for some realtime tracking.<br/>\nex: nicolas is typing ...', max_length=4096)),
                ('i_help', models.TextField(blank=True, default='', help_text='Long help text for the action', verbose_name='Help Text')),
                ('i_success', models.CharField(default='You did ACTION on ITEM', help_text='Confirmation message <br/>\nex: Your invitation to TARGET has been sent !\n', max_length=4096, verbose_name='Success message')),
                ('other_success', models.CharField(default='ACTOR did ACTION on ITEM', help_text='Confirmation message <br/>\nex: ACTOR invitation to TARGET has been sent !\n', max_length=4096)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panels', to='rules.Action')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
    ]
