# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='email',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.CharField(blank=True, default='You did STATUS on ITEM', max_length=4096, null=True, verbose_name='for actor'),
        ),
        migrations.AddField(
            model_name='notification',
            name='others',
            field=models.CharField(blank=True, default='ACTOR did STATUS on ITEM', max_length=4096, null=True, verbose_name='for others'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(blank=True, default='ACTOR did STATUS on ITEM', max_length=4096, null=True, verbose_name='for target'),
        ),
    ]
