# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0002_auto_20180606_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='actor',
            new_name='for_actor',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='others',
            new_name='for_others',
        ),
        migrations.AddField(
            model_name='notification',
            name='for_target',
            field=models.CharField(blank=True, default='ACTOR did STATUS on ITEM', max_length=4096, null=True, verbose_name='for target'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_targets', to='rules.Type', verbose_name='tell'),
        ),
    ]
