# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_auto_20180612_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='discards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grammar.Notification', verbose_name='Discards ...'),
        ),
    ]
