# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0006_auto_20180619_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='ajax',
            field=models.BooleanField(default=True, verbose_name='Automatic ajax bound'),
        ),
    ]
