# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0008_auto_20180628_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='discards',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discarding', to='grammar.Notification', verbose_name='Discards ...'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='rules.Status', verbose_name='When'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_targets', to='rules.Type', verbose_name='tell'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='rules.Type', verbose_name='on a'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='webhook',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='webhooks.Webhook', verbose_name='Webhook'),
        ),
    ]
