# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0009_auto_20180715_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='dialog',
            field=models.BooleanField(default=False, verbose_name='Action is a dialog'),
        ),
    ]
