# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0010_panel_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_actor',
            field=models.CharField(blank=True, default='You did STATUS on ITEM', max_length=4096, null=True, verbose_name='Event actor - deprecated'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='for_others',
            field=models.CharField(blank=True, default='ACTOR did STATUS on ITEM', max_length=4096, null=True, verbose_name='Event observed'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='for_target',
            field=models.CharField(blank=True, default='You did STATUS on ITEM', max_length=4096, null=True, verbose_name='Notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Webhook message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=156, verbose_name='Webhook title'),
        ),
    ]
