# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('akey', models.CharField(blank=True, max_length=36, null=True)),
                ('origin', models.CharField(blank=True, max_length=36, null=True)),
                ('action', models.CharField(blank=True, max_length=36, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('name', models.CharField(max_length=128)),
                ('cname', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('name', models.CharField(max_length=128)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='ilot.Organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('akey', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ilot.Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('name', models.CharField(max_length=128)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='ilot.Organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.AddField(
            model_name='authorization',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='ilot.Organization'),
        ),
    ]
