# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='payload',
            field=models.TextField(default='{}'),
        ),
    ]
