# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
        ('ilot', '0002_authorization_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webhooks.Webhook'),
        ),
    ]
