# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0003_organization_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='iteration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('organization', 'iteration')]),
        ),
    ]
