# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0005_auto_20180607_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ilot.Organization'),
        ),
    ]
