# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0007_auto_20180608_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='akey',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
