# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0008_organization_akey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('cname', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('item', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='akey',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='application',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='content',
        ),
        migrations.AddField(
            model_name='interface',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='ilot.Organization'),
        ),
    ]
