# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0009_auto_20180608_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='content',
            field=models.TextField(default='{% extends "index.html" %}'),
        ),
    ]
