# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_attribute_regexp_error'),
        ('ilot', '0011_auto_20180615_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rules.Action'),
        ),
    ]
