# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0012_interface_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='item',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
