# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0015_auto_20180715_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='repository',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
