# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('cname', models.CharField(max_length=64, unique=True)),
                ('path', models.CharField(max_length=512, unique=True)),
                ('settings', models.TextField(default='{}')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('capacity', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=80)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frontends', to='cloud.Container')),
            ],
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('port', models.IntegerField()),
                ('status', models.CharField(default='unknown', max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='cloud.Application')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='cloud.Container')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.AddField(
            model_name='application',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cloud.Container'),
        ),
        migrations.AlterUniqueTogether(
            name='frontend',
            unique_together=set([('ip', 'port', 'container')]),
        ),
    ]
