# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='path',
            field=models.CharField(max_length=512),
        ),
    ]
