# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('ilot', '0016_interface_repository'),
        ('cloud', '0002_auto_20180720_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('path', models.CharField(max_length=512)),
                ('settings', models.TextField(default='{}')),
                ('enabled', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='cloud.Container')),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='ilot.Interface')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='application',
            name='container',
        ),
        migrations.RemoveField(
            model_name='process',
            name='application',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='process',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='cloud.Service'),
        ),
    ]
