# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grammar', '__first__'),
        ('rules', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPath',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('akey', models.CharField(max_length=128)),
                ('action', models.CharField(blank=True, max_length=36, null=True)),
                ('locale', models.CharField(max_length=36)),
                ('geohash', models.CharField(blank=True, max_length=12, null=True)),
                ('data', models.TextField(blank=True, default='{}', null=True)),
                ('context', models.CharField(default='', max_length=36, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InferedType',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('todo', models.BooleanField(default=False, verbose_name='Is Todo')),
                ('email', models.BooleanField(default=False, verbose_name='Send email')),
                ('sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('notification', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_typing', to='grammar.Notification')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typed_meta', to='rules.Type')),
            ],
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('datapath_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.DataPath')),
                ('status', models.CharField(max_length=65)),
                ('order', models.IntegerField(default=0)),
                ('target', models.CharField(max_length=36)),
                ('behavior', models.CharField(blank=True, default='', max_length=36)),
                ('type', models.CharField(blank=True, max_length=36)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.datapath',),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('moderation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Moderation')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, max_length=65)),
                ('title', models.CharField(blank=True, max_length=156)),
                ('description', models.TextField(blank=True)),
                ('template', models.CharField(blank=True, default='', max_length=36)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.moderation', ilot.core.models.GantChartMixin),
        ),
        migrations.AddField(
            model_name='moderation',
            name='origin',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Moderation'),
        ),
        migrations.AddField(
            model_name='inferedtype',
            name='actor',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_types', to='core.Moderation'),
        ),
        migrations.AddField(
            model_name='inferedtype',
            name='context',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_typed', to='core.Moderation'),
        ),
        migrations.AddField(
            model_name='inferedtype',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_typing', to='core.Moderation'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('translation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Translation')),
            ],
            options={
                'ordering': ('order',),
            },
            bases=('core.translation',),
        ),
        migrations.AlterUniqueTogether(
            name='inferedtype',
            unique_together=set([('context', 'actor', 'type')]),
        ),
        migrations.AddField(
            model_name='translation',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='related',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='core.Item'),
        ),
    ]
