# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180603_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferedtype',
            name='status',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
    ]
