# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180605_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='slug',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
