# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_translation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='label',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AddField(
            model_name='translation',
            name='slug',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='translation',
            name='title',
            field=models.CharField(blank=True, max_length=156),
        ),
    ]
