# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180607_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='label',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='title',
        ),
    ]
