# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180608_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferedtype',
            name='email',
        ),
        migrations.RemoveField(
            model_name='moderation',
            name='behavior',
        ),
        migrations.AlterField(
            model_name='moderation',
            name='origin',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='core.Moderation'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='related',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Item'),
        ),
    ]
