# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180619_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferedtype',
            name='notification',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='grammar.Notification'),
        ),
        migrations.AlterUniqueTogether(
            name='inferedtype',
            unique_together=set([]),
        ),
    ]
