# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ilot.core.manager
import ilot.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0006_auto_20180619_1701'),
        ('core', '0012_auto_20180619_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.CharField(default=ilot.core.manager.AppManager.get_new_uuid, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('ref_time', models.BigIntegerField(default=ilot.core.manager.AppManager.get_ref_time, editable=False)),
                ('created_date', models.DateTimeField(default=ilot.core.manager.AppManager.get_valid_time, editable=False, verbose_name='created on')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified on')),
                ('sent', models.BooleanField(default=False, verbose_name='Is sent')),
            ],
            options={
                'abstract': False,
            },
            bases=(ilot.core.models.ModelDiffMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='inferedtype',
            name='notification',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='grammar.Notification'),
        ),
        migrations.AddField(
            model_name='notif',
            name='context',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to='core.InferedType'),
        ),
        migrations.AddField(
            model_name='notif',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to='core.Moderation'),
        ),
        migrations.AddField(
            model_name='notif',
            name='rule',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrules', to='grammar.Notification'),
        ),
    ]
