# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180619_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferedtype',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='inferedtype',
            name='context',
        ),
        migrations.RemoveField(
            model_name='inferedtype',
            name='event',
        ),
        migrations.RemoveField(
            model_name='inferedtype',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='inferedtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='context',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='event',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='rule',
        ),
        migrations.DeleteModel(
            name='InferedType',
        ),
        migrations.DeleteModel(
            name='Notif',
        ),
    ]
